# Generated by Django 4.1 on 2025-11-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('rg', models.CharField(blank=True, max_length=30, null=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_social', models.CharField(blank=True, max_length=40, null=True)),
                ('genero', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('perfil', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_subsidiado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('url_imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=15)),
                ('logradouro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('fk_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associado')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('fk_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficio')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associado')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('url_imagem_capa', models.CharField(blank=True, max_length=100, null=True)),
                ('destaque', models.CharField(choices=[('nenhum', 'Nenhum'), ('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('maximo', 'Máximo')], default='nenhum', max_length=10)),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='GestorBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('ie', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('fantasia', models.CharField(blank=True, max_length=50, null=True)),
                ('contato', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('fk_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
                ('fk_telefone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fk_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.associado')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
            ],
        ),
        migrations.AddField(
            model_name='associado',
            name='fk_beneficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.beneficio'),
        ),
    ]
