# Generated by Django 4.1 on 2025-11-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_noticia_url_imagem_capa_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficio',
            name='url_imagem',
        ),
    ]
